### ISSUE TITLE
Default version is set to 3.0.4, which doesn't exist

### ISSUE THREAD

**Issue by AndreasVerhoeven** [build-xcframeworks/libressl#1]
```
if [ -z "$LIBRESSL" ]
then
  LIBRESSL=3.0.4
  #LIBRESSL=3.1.4
  #LIBRESSL=3.2.1
fi
```
Version 3.0.4 doesn't exist :) It's 3.0.2. Running the script by default makes it error directly

**Comment by niklassaers** [comment]
Doh, thanks for bringing it to my attention. A typo that had crept in. Reverted it back to 3.0.2 :-)

**Comment by AndreasVerhoeven** [comment]
Thank you for fixing this and providing the script in the first place!

As a unrelated side question, have you been able to compile this under Xcode 11? I see the release binaries are all Xcode 12: I'm running into issues where the compile process stops on the configure when reaching the mac parts.

**Comment by niklassaers** [comment]
Yes, Xcode 11 is supported just fine. But it won’t be able to compile for Apple Silicon. You can do like this:

export BUILD_TARGETS="simulator_x86_64:catalyst_x86_64:macos_x86_64:ios-arm64”
export LINK_TARGETS="simulator_x86_64:catalyst_x86_64:macos_x86_64:ios-arm64”
bash libressl.sh
